#!/bin/bash
# Bundle libraries for Debian package
# This script is auto-generated by build_deb.sh

set -e

EXEC_PATH="$1"
LIB_TEMP_DIR="$2"

if [ -z "$EXEC_PATH" ] || [ -z "$LIB_TEMP_DIR" ]; then
    echo "Usage: $0 <executable> <lib_dir>"
    exit 1
fi

if [ ! -f "$EXEC_PATH" ]; then
    echo "Error: Executable not found: $EXEC_PATH"
    exit 1
fi

mkdir -p "$LIB_TEMP_DIR"

echo "Bundling libraries from $EXEC_PATH..."

# Copy libraries from build directory
BUILD_LIB_DIR=$(dirname "$EXEC_PATH")/../lib
if [ -d "$BUILD_LIB_DIR" ]; then
    cp -L "$BUILD_LIB_DIR"/*.so* "$LIB_TEMP_DIR/" 2>/dev/null || true
fi

# Copy CVEDIX SDK libraries if available
if [ -d "/opt/cvedix/lib" ]; then
    cp -L /opt/cvedix/lib/libcvedix*.so* "$LIB_TEMP_DIR/" 2>/dev/null || true
    cp -L /opt/cvedix/lib/libtinyexpr.so* "$LIB_TEMP_DIR/" 2>/dev/null || true
fi

# Copy CUDA libraries if available (for GPU acceleration support)
# Detect CUDA installation from common paths
CUDA_LIB_PATHS=(
    "/usr/local/cuda/lib64"
    "/usr/local/cuda/lib"
    "/usr/lib/x86_64-linux-gnu"
    "/opt/cuda/lib64"
    "/opt/cuda/lib"
)

CUDA_LIBS=(
    "libcublas.so*"
    "libcublasLt.so*"
    "libcurand.so*"
    "libcusolver.so*"
    "libcufft.so*"
    "libcusparse.so*"
    "libcudart.so*"
    "libnvrtc.so*"
    "libnvjitlink.so*"
)

CUDA_FOUND=false
for cuda_path in "${CUDA_LIB_PATHS[@]}"; do
    if [ -d "$cuda_path" ]; then
        # Check if any CUDA libraries exist in this path
        for cuda_lib_pattern in "${CUDA_LIBS[@]}"; do
            if find "$cuda_path" -maxdepth 1 -name "$cuda_lib_pattern" -type f 2>/dev/null | grep -q .; then
                CUDA_FOUND=true
                # Find and copy CUDA libraries
                find "$cuda_path" -maxdepth 1 -name "$cuda_lib_pattern" -type f 2>/dev/null | while read cuda_lib; do
                    if [ -f "$cuda_lib" ]; then
                        libname=$(basename "$cuda_lib")
                        if [ ! -f "$LIB_TEMP_DIR/$libname" ]; then
                            echo "  Copying CUDA library $libname from $cuda_path..."
                            cp -L "$cuda_lib" "$LIB_TEMP_DIR/" 2>/dev/null || true
                        fi
                    fi
                done
            fi
        done
    fi
done

if [ "$CUDA_FOUND" = true ]; then
    echo "  CUDA libraries bundled successfully"
fi

# Copy other required libraries from ldd output (including OpenCV and GStreamer for full package)
# Bundle all required libraries for a self-contained package
ldd "$EXEC_PATH" 2>/dev/null | grep -v "not found" | awk '{print $3}' | grep -v "^$" | sort -u | while read lib; do
    if [ -f "$lib" ]; then
        libname=$(basename "$lib")

        # Skip system libraries
        case "$libname" in
            libc.so*|libm.so*|libpthread.so*|libdl.so*|libgcc_s.so*|libstdc++.so*|ld-linux*)
                continue
                ;;
            *)
                if [ ! -f "$LIB_TEMP_DIR/$libname" ]; then
                    # Copy all required libraries including OpenCV and GStreamer
                    # Bundle from all paths (including /usr/lib, /lib/x86_64-linux-gnu, etc.)
                    echo "  Copying $libname from $lib..."
                    cp -L "$lib" "$LIB_TEMP_DIR/" 2>/dev/null || true
                fi
                ;;
        esac
    fi
done

# Copy symlinks
for lib in "$LIB_TEMP_DIR"/*.so*; do
    if [ -L "$lib" ] 2>/dev/null; then
        target=$(readlink -f "$lib")
        if [ -f "$target" ] && [ ! -f "$LIB_TEMP_DIR/$(basename "$target")" ]; then
            cp -L "$target" "$LIB_TEMP_DIR/" 2>/dev/null || true
        fi
    fi
done

echo "Libraries bundled successfully."
