#!/bin/bash
# Bundle libraries for Debian package
# This script is auto-generated by build_deb.sh

set -e

EXEC_PATH="$1"
LIB_TEMP_DIR="$2"

if [ -z "$EXEC_PATH" ] || [ -z "$LIB_TEMP_DIR" ]; then
    echo "Usage: $0 <executable> <lib_dir>"
    exit 1
fi

if [ ! -f "$EXEC_PATH" ]; then
    echo "Error: Executable not found: $EXEC_PATH"
    exit 1
fi

mkdir -p "$LIB_TEMP_DIR"

echo "Bundling libraries from $EXEC_PATH..."

# Copy libraries from build directory
BUILD_LIB_DIR=$(dirname "$EXEC_PATH")/../lib
if [ -d "$BUILD_LIB_DIR" ]; then
    cp -L "$BUILD_LIB_DIR"/*.so* "$LIB_TEMP_DIR/" 2>/dev/null || true
fi

# Copy CVEDIX SDK libraries if available
if [ -d "/opt/cvedix/lib" ]; then
    cp -L /opt/cvedix/lib/libcvedix*.so* "$LIB_TEMP_DIR/" 2>/dev/null || true
    cp -L /opt/cvedix/lib/libtinyexpr.so* "$LIB_TEMP_DIR/" 2>/dev/null || true
fi

# Copy other required libraries from ldd output (excluding OpenCV and GStreamer)
# OpenCV and GStreamer should be installed by user via package dependencies
ldd "$EXEC_PATH" 2>/dev/null | grep -v "not found" | awk '{print $3}' | grep -v "^$" | sort -u | while read lib; do
    if [ -f "$lib" ]; then
        libname=$(basename "$lib")
        
        # Skip system libraries
        case "$libname" in
            libc.so*|libm.so*|libpthread.so*|libdl.so*|libgcc_s.so*|libstdc++.so*|ld-linux*)
                continue
                ;;
            libopencv*.so*|libgst*.so*|libgstrtspserver*.so*)
                # Skip OpenCV and GStreamer - user must install via package dependencies
                continue
                ;;
            *)
                if [ ! -f "$LIB_TEMP_DIR/$libname" ]; then
                    # Copy custom libraries (not in standard system paths, or from /opt)
                    case "$lib" in
                        /lib/*|/usr/lib/*|/usr/local/lib/*)
                            case "$lib" in
                                /opt/*)
                                    cp -L "$lib" "$LIB_TEMP_DIR/" 2>/dev/null || true
                                    ;;
                            esac
                            ;;
                        *)
                            cp -L "$lib" "$LIB_TEMP_DIR/" 2>/dev/null || true
                            ;;
                    esac
                fi
                ;;
        esac
    fi
done

# Copy symlinks
for lib in "$LIB_TEMP_DIR"/*.so*; do
    if [ -L "$lib" ] 2>/dev/null; then
        target=$(readlink -f "$lib")
        if [ -f "$target" ] && [ ! -f "$LIB_TEMP_DIR/$(basename "$target")" ]; then
            cp -L "$target" "$LIB_TEMP_DIR/" 2>/dev/null || true
        fi
    fi
done

echo "Libraries bundled successfully."
